### ISSUE TITLE
Use import instead of Object

### ISSUE THREAD

**Issue by kumamaki** [SasanFarrokh/vite-plugin-multi-device#1]
Hey man. Not sure if you've been already through this or not.  
A suggestion, maybe you want to use `import.meta.device` instead of `Object.DEVICE` to stay with Vite's way of handling these cases?

PS. I don't know if that's possible for plugins or there is any caveat to it.

FYI: https://vitejs.dev/guide/env-and-mode.html#env-variables

**Comment by SasanFarrokh** [comment]
Yeah it works, but the thing is it does not work inside template tags,

```html
<template>
<div v-if="import.meta.device"></div> this does not work
</template>
```

cause vue automatically prefixes everything inside template with a `_ctx` or `this`.

So i chose `Object` because it's in the vue compiler white list:

https://github.com/vuejs/vue-next/blob/master/packages/shared/src/globalsWhitelist.ts


it'll completely replaced by rollup , and the dead tree code will be eliminated, so there is no worries, 

But i think it's better to purpose to Vue, somehow let us add some extra tokens to the whitelist.
